In [1]:
# I only need the following line since I'm using remote VS Code
%cd "/arc/home/IsaacCheng/CASTOR/ETC/notebooks"

import numpy as np
import pandas as pd
import astropy.units as u
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.display import display

# Import my own modules
import sys

sys.path.append("../")
from castor_etc.snr import calc_snr_AB

/arc/home/IsaacCheng/CASTOR/ETC/notebooks

In [2]:
ab_mags = np.arange(22, 29, 0.5)
times = calc_snr_AB(source_AB_mags=ab_mags, snr=5, darkcurrent=0)
snrs = dict.fromkeys(times.keys())
for band, time in times.items():
    snrs[band] = calc_snr_AB(
        source_AB_mags=ab_mags, t=time, passbands=band, darkcurrent=0
    )
display(pd.DataFrame(times, index=ab_mags))
display(pd.DataFrame(snrs, index=ab_mags))

               uv            u            g
22.0     4.479899     2.889007     2.728179
22.5     7.102137     4.589165     4.351841
23.0    11.261093     7.299487     6.967709
23.5    17.860103    11.634726    11.221162
24.0    28.337700    18.605652    18.235471
24.5    44.991009    29.906622    30.048859
25.0    71.504031    48.458337    50.559926
25.5   113.824605    79.493009    87.693076
26.0   181.654724   132.861949   158.587982
26.5   291.067556   228.241583   302.381458
27.0   469.306354   407.472243   611.967921
27.5   764.065849   764.777423  1312.813872
28.0  1262.555087  1521.783862  2958.551684
28.5  2133.130050  3213.804787  6918.344382

       uv    u    g
22.0  5.0  5.0  5.0
22.5  5.0  5.0  5.0
23.0  5.0  5.0  5.0
23.5  5.0  5.0  5.0
24.0  5.0  5.0  5.0
24.5  5.0  5.0  5.0
25.0  5.0  5.0  5.0
25.5  5.0  5.0  5.0
26.0  5.0  5.0  5.0
26.5  5.0  5.0  5.0
27.0  5.0  5.0  5.0
27.5  5.0  5.0  5.0
28.0  5.0  5.0  5.0
28.5  5.0  5.0  5.0

In [2]:
NPIX = 3
INCLUDE_GEOCORONAL = True
ab_mags = np.arange(22, 29, 0.5)
times = calc_snr_AB(source_AB_mags=ab_mags, snr=5, darkcurrent=0.01, npix=NPIX, include_geocoronal=INCLUDE_GEOCORONAL)
snrs = dict.fromkeys(times.keys())
for band, time in times.items():
    snrs[band] = calc_snr_AB(
        source_AB_mags=ab_mags,
        t=time,
        passbands=band,
        darkcurrent=0.01,
        npix=NPIX,
        include_geocoronal=INCLUDE_GEOCORONAL,
    )
display(pd.DataFrame(times, index=ab_mags))
display(pd.DataFrame(snrs, index=ab_mags))

{'uv': array([7.79830111, 4.92039536, 3.10455959, 1.95884467, 1.23594743,
       0.77983011, 0.49203954, 0.31045596, 0.19588447, 0.12359474,
       0.07798301, 0.04920395, 0.0310456 , 0.01958845]), 'u': array([12.1338885 ,  7.65596607,  4.83058802,  3.04789499,  1.92309173,
        1.21338885,  0.76559661,  0.4830588 ,  0.3047895 ,  0.19230917,
        0.12133889,  0.07655966,  0.04830588,  0.03047895]), 'g': array([12.94195841,  8.16582371,  5.15228645,  3.25087297,  2.05116218,
        1.29419584,  0.81658237,  0.51522864,  0.3250873 ,  0.20511622,
        0.12941958,  0.08165824,  0.05152286,  0.03250873])}
{'uv': array([7.79830111, 4.92039536, 3.10455959, 1.95884467, 1.23594743,
       0.77983011, 0.49203954, 0.31045596, 0.19588447, 0.12359474,
       0.07798301, 0.04920395, 0.0310456 , 0.01958845])}
{'u': array([12.1338885 ,  7.65596607,  4.83058802,  3.04789499,  1.92309173,
        1.21338885,  0.76559661,  0.4830588 ,  0.3047895 ,  0.19230917,
        0.12133889,  0.07655966,  0.04830588,  0.03047895])}
{'g': array([12.94195841,  8.16582371,  5.15228645,  3.25087297,  2.05116218,
        1.29419584,  0.81658237,  0.51522864,  0.3250873 ,  0.20511622,
        0.12941958,  0.08165824,  0.05152286,  0.03250873])}

               uv            u            g
22.0     4.357880     2.804450     2.646348
22.5     6.921539     4.457676     4.222139
23.0    11.007027     7.097449     6.762115
23.5    17.538387    11.330553    10.895200
24.0    28.031801    18.164100    17.718413
24.5    45.021099    29.309577    29.227647
25.0    72.854867    47.773846    49.251501
25.5   119.276149    79.078874    85.591695
26.0   198.749454   133.935835   155.147979
26.5   339.894116   234.432825   296.514403
27.0   602.948514   428.946501   601.212790
27.5  1122.261230   828.898512  1291.123881
28.0  2211.399822  1699.922783  2910.651300
28.5  4623.845410  3687.856502  6805.611428

       uv    u    g
22.0  5.0  5.0  5.0
22.5  5.0  5.0  5.0
23.0  5.0  5.0  5.0
23.5  5.0  5.0  5.0
24.0  5.0  5.0  5.0
24.5  5.0  5.0  5.0
25.0  5.0  5.0  5.0
25.5  5.0  5.0  5.0
26.0  5.0  5.0  5.0
26.5  5.0  5.0  5.0
27.0  5.0  5.0  5.0
27.5  5.0  5.0  5.0
28.0  5.0  5.0  5.0
28.5  5.0  5.0  5.0